name: "Bug report"
description: "Report an issue to help the project improve."
title: "..."
labels:
  - "bug"
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Please enter an explicit description of your issue"
      placeholder: "Short and explicit description of your incident..."
    validations:
      required: true
  - type: textarea
    id: reprod
    attributes:
      label: "Reproduction steps"
      description: "Steps to reproduce the behavior"
      value: |
        1. Go to `...`
        2. Click on `....`
        3. Scroll down to `....`
        4. See Error.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: "Logs"
      description: "Please Provide the .zip, By Exporting a log. (THIS IS REQUIRED)"
      placeholder: "Press `Paste, drop, or click to add files` to add"
    validations:
      required: false
  - type: input
    id: Snapchat-Version
    attributes:
      label: "Snapchat Version"
      description: "On which Snapchat version is this happening?"
      placeholder: "e.g. 12.35.0.45"
    validations:
      required: true
  - type: input
    id: SE-Extended-Version
    attributes:
      label: "SE Extended Version"
      description: "On which SE Extended version is this happening?"
      placeholder: "e.g. 1.0.0"
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: "Agreement"
      description: "**By creating this issue, I agree to the following terms:**"
      options:
        - label: "This is not a bug regarding Snapchat+."
        - label: "I have provided a detailed description of the issue."
        - label: "I have attached a log if deemed necessary."
        - label: "This issue is not a duplicate."
    validations:
      required: true
